version: '3.8'

services:
  simulador-ace:
    build: .
    container_name: simulador-ace
    ports:
      - "8082:80"
    env_file:
      - .env
    volumes:
      - ./api-usage.log:/app/api-usage.log
    restart: unless-stopped
